# Spreetail Import Report
_Generated by: Spreetail CSV Importer_
_Date: 2026-06-14_
_File: Expenses Export.csv_

## Import Summary
- **Total Rows Parsed:** 43
- **Rows Processed Automatically:** 29
- **Anomalies Detected:** 14
- **Rows Skipped:** 1
- **Settlements Created:** 1
- **Expenses Created:** 41

---

## Detected Anomalies & Resolutions

| Row | Date | Description | Anomaly Detected | Action Taken / Resolution |
|---|---|---|---|---|
| 6 | 08-02-2026 | dinner - marina bites | **DUPLICATE_EXPENSE** (Matches Row 5 "Dinner at Marina Bites" by date, payer, and amount) | Flagged for user review. User chose to **SKIP** Row 6 and keep Row 5. |
| 7 | 10-02-2026 | Electricity Feb | **NUMBER_FORMAT** (Amount "1,200" contains comma) | Safely parsed to `1200.00` automatically. |
| 11 | 18-02-2026 | Groceries DMart | **UNKNOWN_MEMBER** (Payer "Priya S" not found exactly) | Mapped via user prompt to existing user "Priya". |
| 14 | 25-02-2026 | Rohan paid Aisha back | **SETTLEMENT_AS_EXPENSE** (Missing participants, notes indicate settlement) | Reclassified as a `Settlement` record. Payer: Rohan, Receiver: Aisha. |
| 15 | 28-02-2026 | Pizza Friday | **PERCENTAGE_SUM_INVALID** (Sum is 110%) | Flagged for review. User manually corrected Meera's share to 10% to sum to 100%. |
| 23 | 11-03-2026 | Parasailing | **UNKNOWN_MEMBER** ("Dev's friend Kabir") | Created `GuestParticipant` named "Kabir" tied to Dev. |
| 24, 25 | 11-03-2026 | Thalassa dinner | **POSSIBLE_DUPLICATE** (Similar date, participants, different amounts) | Flagged for review. User approved both (decided they were separate bills). |
| 26 | 12-03-2026 | Parasailing refund | **NEGATIVE_AMOUNT** (-30 USD) | Converted to `TransactionType: REFUND` with absolute amount 30 USD. |
| 27 | Mar-14 | Airport cab | **AMBIGUOUS_DATE** ("Mar-14") | Parsed safely to `14-03-2026`. Payer "rohan " trimmed. |
| 28 | 15-03-2026 | Groceries DMart | **MISSING_CURRENCY** (Empty currency field) | Flagged for review. User approved default to group base currency `INR`. |
| 31 | 22-03-2026 | Dinner order Swiggy | **ZERO_AMOUNT** (Amount is 0) | Flagged for review. User chose to **SKIP** row. |
| 32 | 25-03-2026 | Weekend brunch | **PERCENTAGE_SUM_INVALID** (Sum is 110%) | Flagged for review. User corrected percentages. |
| 34 | 04-05-2026 | Deep cleaning service | **AMBIGUOUS_DATE** (04-05 could be April 5 or May 4) | Flagged for review. User confirmed date as `05-04-2026` (April 5th). |
| 36 | 02-04-2026 | Groceries BigBasket | **INACTIVE_MEMBER_AT_DATE** (Meera included in split, but left in March) | Flagged for review. User chose to recalculate split equally among remaining active members. |
| 42 | 18-04-2026 | Furniture | **INVALID_SPLIT_TYPE** (Type "equal" but shares provided) | Flagged for review. User overrode split_type to `SHARE`. |

---
_End of Report_
